### PR TITLE
Added two more parameters to the psk importer

### PR DESCRIPTION
**Pull request by ProtoByter**
Added scale parameter and shade smooth/flat parameter

### CODE REVIEW

**Comment by Blenux** [comment]
Nice feature request, I was gonna ask about a scaling parameter but didn't get around to it, I've added it to Befzz code, works good, he probably will need to remove the scale down option now if he merges it, though I notice that wasn't in yours.

**Comment by Bobrow** [comment]
Thanks, took me quite a while as I haven't used blender python api much and the idea came from the fact that in blender terms the models were about fifty times to large (when using fortnite models they were >100m tall whilst a average person is 2m tall), I was using the version from the latest package so I didn't see any kind of scale down option

**Comment by Blenux** [comment]
Did you use latest branch? because there is vertex color support also, with this I have to set scale to 91 to match the UE4 Mannequin, untick scale down and the scaling gets wonky. 

Annotation 2019-12-30 123318

Annotation 2019-12-30 123556

**Comment by Bobrow** [comment]
I don't think I do have the latest branch

**Comment by Blenux** [comment]
Yeah you want to use this one, 

https://github.com/Befzz/blender3d_import_psk_psa/tree/latest/addons

**Pull request closed without merging**
